name: Ejecutar Saldo_Inventario.py cada hora

on:
  schedule:
    - cron: "0 * * * *"  # Se ejecuta cada hora a los 0 minutos (UTC)

jobs:
  run-script:
    runs-on: Ubuntu-22.04
    steps:
      - name: Obtener código
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ejecutar script
        run: python Saldo_Inventario.py
